name: Publish to PyPI

on:
  workflow_call:
    secrets:
      TWINE_USERNAME:
        required: true
      TWINE_PASSWORD:
        required: true

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel twine
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: python setup.py sdist
      - name: Upload to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}